// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class acc_level
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string auth_area_id { get; set; }

    public long? business_id { get; set; }

    public DateTime? end_date { get; set; }

    public bool? init_flag { get; set; }

    public string name { get; set; }

    public DateTime? start_date { get; set; }

    public string timeseg_id { get; set; }

    public virtual ICollection<acc_level_dept> acc_level_depts { get; set; } = new List<acc_level_dept>();

    public virtual ICollection<acc_level_door> acc_level_doors { get; set; } = new List<acc_level_door>();

    public virtual ICollection<acc_level_person> acc_level_people { get; set; } = new List<acc_level_person>();
}