// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class acc_alarm_monitor
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string area_name { get; set; }

    public string dev_alias { get; set; }

    public string dev_sn { get; set; }

    public string event_name { get; set; }

    public long? event_num { get; set; }

    public string event_point_name { get; set; }

    public DateTime? event_time { get; set; }

    public string name { get; set; }

    public string pin { get; set; }

    public short? priority { get; set; }

    public string reader_name { get; set; }

    public short? status { get; set; }

    public virtual ICollection<acc_alarmmonitor_history> acc_alarmmonitor_histories { get; set; } = new List<acc_alarmmonitor_history>();
}