// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class acc_door
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public short action_interval { get; set; }

    public string active_timeseg_id { get; set; }

    public string allow_suaccess_lock { get; set; }

    public bool back_lock { get; set; }

    public short? combopen_interval { get; set; }

    public short? delay_open_time { get; set; }

    public short door_no { get; set; }

    public string door_pwd { get; set; }

    public short door_sensor_status { get; set; }

    public bool? enabled { get; set; }

    public short? ext_delay_drivertime { get; set; }

    public string ext_dev_id { get; set; }

    public string force_pwd { get; set; }

    public short? host_status { get; set; }

    public short? in_apb_duration { get; set; }

    public bool? is_disable_audio { get; set; }

    public short? latch_door_type { get; set; }

    public short? latch_time_out { get; set; }

    public string latch_timeseg_id { get; set; }

    public short lock_delay { get; set; }

    public string name { get; set; }

    public string passmode_timeseg_id { get; set; }

    public short? reader_type { get; set; }

    public string rex_button_type { get; set; }

    public string sex_input_mode { get; set; }

    public string sex_supervised_resistor { get; set; }

    public string sen_input_mode { get; set; }

    public string sen_supervised_resistor { get; set; }

    public short? sensor_delay { get; set; }

    public short? slave_status { get; set; }

    public string supper_pwd { get; set; }

    public short verify_mode { get; set; }

    public string wg_input_id { get; set; }

    public short? wg_input_type { get; set; }

    public string wg_output_id { get; set; }

    public short? wg_output_type { get; set; }

    public short? wg_reversed { get; set; }

    public string dev_id { get; set; }

    public virtual ICollection<acc_combopen_door> acc_combopen_doors { get; set; } = new List<acc_combopen_door>();

    public virtual ICollection<acc_door_verifymoderule> acc_door_verifymoderules { get; set; } = new List<acc_door_verifymoderule>();

    public virtual ICollection<acc_firstopen> acc_firstopens { get; set; } = new List<acc_firstopen>();

    public virtual ICollection<acc_level_door> acc_level_doors { get; set; } = new List<acc_level_door>();

    public virtual ICollection<acc_reader> acc_readers { get; set; } = new List<acc_reader>();

    public virtual acc_device dev { get; set; }
}