// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class acc_auxin
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public short aux_no { get; set; }

    public bool? disable { get; set; }

    public string ext_dev_id { get; set; }

    public string input_mode { get; set; }

    public string input_type { get; set; }

    public string name { get; set; }

    public string printer_number { get; set; }

    public string remark { get; set; }

    public string supervised_resistor { get; set; }

    public string timeseg_id { get; set; }

    public string dev_id { get; set; }

    public virtual acc_device dev { get; set; }
}