// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class acc_interlock
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public long? business_id { get; set; }

    public short? interlock_rule { get; set; }

    public short? lock_rule { get; set; }

    public string name { get; set; }

    public string dev_id { get; set; }

    public string trigger_group1 { get; set; }

    public string trigger_group2 { get; set; }

    public virtual acc_device dev { get; set; }

    public virtual acc_triggergroup trigger_group1Navigation { get; set; }

    public virtual acc_triggergroup trigger_group2Navigation { get; set; }
}