// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class acc_triggergroup
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public long? bussiness_id { get; set; }

    public short? type { get; set; }

    public virtual ICollection<acc_antipassback> acc_antipassbacktrigger_group1Navigations { get; set; } = new List<acc_antipassback>();

    public virtual ICollection<acc_antipassback> acc_antipassbacktrigger_group2Navigations { get; set; } = new List<acc_antipassback>();

    public virtual ICollection<acc_interlock> acc_interlocktrigger_group1Navigations { get; set; } = new List<acc_interlock>();

    public virtual ICollection<acc_interlock> acc_interlocktrigger_group2Navigations { get; set; } = new List<acc_interlock>();

    public virtual ICollection<acc_triggergroup_addr> acc_triggergroup_addrs { get; set; } = new List<acc_triggergroup_addr>();
}