// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class acc_muster_point
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public bool activated { get; set; }

    public DateTime? activated_time { get; set; }

    public string email_recipients { get; set; }

    public string interval_time { get; set; }

    public bool? message_notification { get; set; }

    public string message_notification_type { get; set; }

    public string name { get; set; }

    public string remark { get; set; }

    public bool? send_report { get; set; }

    public bool? statistics_visitors { get; set; }

    public virtual ICollection<acc_musterpoint_dept> acc_musterpoint_depts { get; set; } = new List<acc_musterpoint_dept>();

    public virtual ICollection<acc_musterpoint_signpoint> acc_musterpoint_signpoints { get; set; } = new List<acc_musterpoint_signpoint>();
}