// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class acc_timeseg
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public long? business_id { get; set; }

    public DateTime? end_time { get; set; }

    public string friday_end1 { get; set; }

    public string friday_end2 { get; set; }

    public string friday_end3 { get; set; }

    public string friday_start1 { get; set; }

    public string friday_start2 { get; set; }

    public string friday_start3 { get; set; }

    public string holidaytype1_end1 { get; set; }

    public string holidaytype1_end2 { get; set; }

    public string holidaytype1_end3 { get; set; }

    public string holidaytype1_start1 { get; set; }

    public string holidaytype1_start2 { get; set; }

    public string holidaytype1_start3 { get; set; }

    public string holidaytype2_end1 { get; set; }

    public string holidaytype2_end2 { get; set; }

    public string holidaytype2_end3 { get; set; }

    public string holidaytype2_start1 { get; set; }

    public string holidaytype2_start2 { get; set; }

    public string holidaytype2_start3 { get; set; }

    public string holidaytype3_end1 { get; set; }

    public string holidaytype3_end2 { get; set; }

    public string holidaytype3_end3 { get; set; }

    public string holidaytype3_start1 { get; set; }

    public string holidaytype3_start2 { get; set; }

    public string holidaytype3_start3 { get; set; }

    public bool? init_flag { get; set; }

    public string monday_end1 { get; set; }

    public string monday_end2 { get; set; }

    public string monday_end3 { get; set; }

    public string monday_start1 { get; set; }

    public string monday_start2 { get; set; }

    public string monday_start3 { get; set; }

    public string name { get; set; }

    public string remark { get; set; }

    public string saturday_end1 { get; set; }

    public string saturday_end2 { get; set; }

    public string saturday_end3 { get; set; }

    public string saturday_start1 { get; set; }

    public string saturday_start2 { get; set; }

    public string saturday_start3 { get; set; }

    public DateTime? start_time { get; set; }

    public string sunday_end1 { get; set; }

    public string sunday_end2 { get; set; }

    public string sunday_end3 { get; set; }

    public string sunday_start1 { get; set; }

    public string sunday_start2 { get; set; }

    public string sunday_start3 { get; set; }

    public string thursday_end1 { get; set; }

    public string thursday_end2 { get; set; }

    public string thursday_end3 { get; set; }

    public string thursday_start1 { get; set; }

    public string thursday_start2 { get; set; }

    public string thursday_start3 { get; set; }

    public string tuesday_end1 { get; set; }

    public string tuesday_end2 { get; set; }

    public string tuesday_end3 { get; set; }

    public string tuesday_start1 { get; set; }

    public string tuesday_start2 { get; set; }

    public string tuesday_start3 { get; set; }

    public string wednesday_end1 { get; set; }

    public string wednesday_end2 { get; set; }

    public string wednesday_end3 { get; set; }

    public string wednesday_start1 { get; set; }

    public string wednesday_start2 { get; set; }

    public string wednesday_start3 { get; set; }

    public virtual ICollection<acc_verifymode_rule> acc_verifymode_rules { get; set; } = new List<acc_verifymode_rule>();
}