// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class acc_dstime
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public long? bussiness_id { get; set; }

    public short dstime_mode { get; set; }

    public string end_time { get; set; }

    public string end_year { get; set; }

    public bool? init_flag { get; set; }

    public string name { get; set; }

    public string start_time { get; set; }

    public string start_year { get; set; }

    public string time_zone { get; set; }

    public virtual ICollection<acc_device> acc_devices { get; set; } = new List<acc_device>();
}