// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class acc_globalinterlock_group
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public bool is_groupinterlock { get; set; }

    public string name { get; set; }

    public string remark { get; set; }

    public virtual ICollection<acc_globalinterlock_door> acc_globalinterlock_doors { get; set; } = new List<acc_globalinterlock_door>();

    public virtual ICollection<acc_globalinterlock_mid> acc_globalinterlock_mids { get; set; } = new List<acc_globalinterlock_mid>();
}