// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class acc_zone
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string code { get; set; }

    public bool? initflag { get; set; }

    public string name { get; set; }

    public string remark { get; set; }

    public string parent_id { get; set; }

    public virtual ICollection<acc_zone> Inverseparent { get; set; } = new List<acc_zone>();

    public virtual ICollection<acc_globalapb> acc_globalapbs { get; set; } = new List<acc_globalapb>();

    public virtual ICollection<acc_occupancy> acc_occupancies { get; set; } = new List<acc_occupancy>();

    public virtual ICollection<acc_personlimit_zone> acc_personlimit_zones { get; set; } = new List<acc_personlimit_zone>();

    public virtual ICollection<acc_reader_zone> acc_reader_zonefrom_zones { get; set; } = new List<acc_reader_zone>();

    public virtual ICollection<acc_reader_zone> acc_reader_zoneto_zones { get; set; } = new List<acc_reader_zone>();

    public virtual acc_zone parent { get; set; }
}