// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class acc_reader
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public short? comm_address { get; set; }

    public short? comm_type { get; set; }

    public string ext_dev_id { get; set; }

    public string fw_version { get; set; }

    public string ip { get; set; }

    public string mac { get; set; }

    public string multicast { get; set; }

    public string name { get; set; }

    public short? offline_refuse { get; set; }

    public short? port { get; set; }

    public bool? reader_encrypt { get; set; }

    public short reader_no { get; set; }

    public short reader_state { get; set; }

    public short? rs485_protocol_type { get; set; }

    public short? serial_port { get; set; }

    public string sn { get; set; }

    public short? user_lock_fun { get; set; }

    public string wg_inputfmt_id { get; set; }

    public short? wg_reversed { get; set; }

    public string door_id { get; set; }

    public virtual ICollection<acc_reader_option> acc_reader_options { get; set; } = new List<acc_reader_option>();

    public virtual acc_door door { get; set; }
}