// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class acc_globalapb
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public short apb_type { get; set; }

    public short? apply_to { get; set; }

    public short is_reset_apb { get; set; }

    public short? lockout_duration { get; set; }

    public string name { get; set; }

    public short opendoor_rule { get; set; }

    public string reset_time { get; set; }

    public string zone_id { get; set; }

    public virtual ICollection<acc_person_globalapb> acc_person_globalapbs { get; set; } = new List<acc_person_globalapb>();

    public virtual acc_zone zone { get; set; }
}