// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class acc_combopen_person
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public long? business_id { get; set; }

    public string name { get; set; }

    public string remark { get; set; }

    public virtual ICollection<acc_combopen_comb> acc_combopen_combs { get; set; } = new List<acc_combopen_comb>();

    public virtual ICollection<acc_person_combopenperson> acc_person_combopenpeople { get; set; } = new List<acc_person_combopenperson>();
}