// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ACT_HI_TSK_LOG
{
    public decimal ID_ { get; set; }

    public string TYPE_ { get; set; }

    public string TASK_ID_ { get; set; }

    public DateTime TIME_STAMP_ { get; set; }

    public string USER_ID_ { get; set; }

    public string DATA_ { get; set; }

    public string EXECUTION_ID_ { get; set; }

    public string PROC_INST_ID_ { get; set; }

    public string PROC_DEF_ID_ { get; set; }

    public string SCOPE_ID_ { get; set; }

    public string SCOPE_DEFINITION_ID_ { get; set; }

    public string SUB_SCOPE_ID_ { get; set; }

    public string SCOPE_TYPE_ { get; set; }

    public string TENANT_ID_ { get; set; }
}