// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ACT_HI_PROCINST
{
    public string ID_ { get; set; }

    public int? REV_ { get; set; }

    public string PROC_INST_ID_ { get; set; }

    public string BUSINESS_KEY_ { get; set; }

    public string PROC_DEF_ID_ { get; set; }

    public DateTime START_TIME_ { get; set; }

    public DateTime? END_TIME_ { get; set; }

    public decimal? DURATION_ { get; set; }

    public string START_USER_ID_ { get; set; }

    public string START_ACT_ID_ { get; set; }

    public string END_ACT_ID_ { get; set; }

    public string SUPER_PROCESS_INSTANCE_ID_ { get; set; }

    public string DELETE_REASON_ { get; set; }

    public string TENANT_ID_ { get; set; }

    public string NAME_ { get; set; }

    public string CALLBACK_ID_ { get; set; }

    public string CALLBACK_TYPE_ { get; set; }

    public string REFERENCE_ID_ { get; set; }

    public string REFERENCE_TYPE_ { get; set; }

    public string PROPAGATED_STAGE_INST_ID_ { get; set; }

    public string BUSINESS_STATUS_ { get; set; }
}