// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ACT_HI_ENTITYLINK
{
    public string ID_ { get; set; }

    public string LINK_TYPE_ { get; set; }

    public DateTime? CREATE_TIME_ { get; set; }

    public string SCOPE_ID_ { get; set; }

    public string SUB_SCOPE_ID_ { get; set; }

    public string SCOPE_TYPE_ { get; set; }

    public string SCOPE_DEFINITION_ID_ { get; set; }

    public string PARENT_ELEMENT_ID_ { get; set; }

    public string REF_SCOPE_ID_ { get; set; }

    public string REF_SCOPE_TYPE_ { get; set; }

    public string REF_SCOPE_DEFINITION_ID_ { get; set; }

    public string ROOT_SCOPE_ID_ { get; set; }

    public string ROOT_SCOPE_TYPE_ { get; set; }

    public string HIERARCHY_TYPE_ { get; set; }
}