// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ACT_RE_DEPLOYMENT
{
    public string ID_ { get; set; }

    public string NAME_ { get; set; }

    public string CATEGORY_ { get; set; }

    public string KEY_ { get; set; }

    public string TENANT_ID_ { get; set; }

    public DateTime? DEPLOY_TIME_ { get; set; }

    public string DERIVED_FROM_ { get; set; }

    public string DERIVED_FROM_ROOT_ { get; set; }

    public string PARENT_DEPLOYMENT_ID_ { get; set; }

    public string ENGINE_VERSION_ { get; set; }

    public virtual ICollection<ACT_GE_BYTEARRAY> ACT_GE_BYTEARRAYs { get; set; } = new List<ACT_GE_BYTEARRAY>();

    public virtual ICollection<ACT_RE_MODEL> ACT_RE_MODELs { get; set; } = new List<ACT_RE_MODEL>();
}