// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ACT_GE_BYTEARRAY
{
    public string ID_ { get; set; }

    public int? REV_ { get; set; }

    public string NAME_ { get; set; }

    public string DEPLOYMENT_ID_ { get; set; }

    public byte[] BYTES_ { get; set; }

    public byte? GENERATED_ { get; set; }

    public virtual ICollection<ACT_PROCDEF_INFO> ACT_PROCDEF_INFOs { get; set; } = new List<ACT_PROCDEF_INFO>();

    public virtual ICollection<ACT_RE_MODEL> ACT_RE_MODELEDITOR_SOURCE_EXTRA_VALUE_ID_Navigations { get; set; } = new List<ACT_RE_MODEL>();

    public virtual ICollection<ACT_RE_MODEL> ACT_RE_MODELEDITOR_SOURCE_VALUE_ID_Navigations { get; set; } = new List<ACT_RE_MODEL>();

    public virtual ICollection<ACT_RU_DEADLETTER_JOB> ACT_RU_DEADLETTER_JOBCUSTOM_VALUES_ID_Navigations { get; set; } = new List<ACT_RU_DEADLETTER_JOB>();

    public virtual ICollection<ACT_RU_DEADLETTER_JOB> ACT_RU_DEADLETTER_JOBEXCEPTION_STACK_ID_Navigations { get; set; } = new List<ACT_RU_DEADLETTER_JOB>();

    public virtual ICollection<ACT_RU_EXTERNAL_JOB> ACT_RU_EXTERNAL_JOBCUSTOM_VALUES_ID_Navigations { get; set; } = new List<ACT_RU_EXTERNAL_JOB>();

    public virtual ICollection<ACT_RU_EXTERNAL_JOB> ACT_RU_EXTERNAL_JOBEXCEPTION_STACK_ID_Navigations { get; set; } = new List<ACT_RU_EXTERNAL_JOB>();

    public virtual ICollection<ACT_RU_JOB> ACT_RU_JOBCUSTOM_VALUES_ID_Navigations { get; set; } = new List<ACT_RU_JOB>();

    public virtual ICollection<ACT_RU_JOB> ACT_RU_JOBEXCEPTION_STACK_ID_Navigations { get; set; } = new List<ACT_RU_JOB>();

    public virtual ICollection<ACT_RU_SUSPENDED_JOB> ACT_RU_SUSPENDED_JOBCUSTOM_VALUES_ID_Navigations { get; set; } = new List<ACT_RU_SUSPENDED_JOB>();

    public virtual ICollection<ACT_RU_SUSPENDED_JOB> ACT_RU_SUSPENDED_JOBEXCEPTION_STACK_ID_Navigations { get; set; } = new List<ACT_RU_SUSPENDED_JOB>();

    public virtual ICollection<ACT_RU_TIMER_JOB> ACT_RU_TIMER_JOBCUSTOM_VALUES_ID_Navigations { get; set; } = new List<ACT_RU_TIMER_JOB>();

    public virtual ICollection<ACT_RU_TIMER_JOB> ACT_RU_TIMER_JOBEXCEPTION_STACK_ID_Navigations { get; set; } = new List<ACT_RU_TIMER_JOB>();

    public virtual ICollection<ACT_RU_VARIABLE> ACT_RU_VARIABLEs { get; set; } = new List<ACT_RU_VARIABLE>();

    public virtual ACT_RE_DEPLOYMENT DEPLOYMENT_ID_Navigation { get; set; }
}