// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ACT_RE_MODEL
{
    public string ID_ { get; set; }

    public int? REV_ { get; set; }

    public string NAME_ { get; set; }

    public string KEY_ { get; set; }

    public string CATEGORY_ { get; set; }

    public DateTime? CREATE_TIME_ { get; set; }

    public DateTime? LAST_UPDATE_TIME_ { get; set; }

    public int? VERSION_ { get; set; }

    public string META_INFO_ { get; set; }

    public string DEPLOYMENT_ID_ { get; set; }

    public string EDITOR_SOURCE_VALUE_ID_ { get; set; }

    public string EDITOR_SOURCE_EXTRA_VALUE_ID_ { get; set; }

    public string TENANT_ID_ { get; set; }

    public virtual ACT_RE_DEPLOYMENT DEPLOYMENT_ID_Navigation { get; set; }

    public virtual ACT_GE_BYTEARRAY EDITOR_SOURCE_EXTRA_VALUE_ID_Navigation { get; set; }

    public virtual ACT_GE_BYTEARRAY EDITOR_SOURCE_VALUE_ID_Navigation { get; set; }
}