// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ACT_RE_PROCDEF
{
    public string ID_ { get; set; }

    public int? REV_ { get; set; }

    public string CATEGORY_ { get; set; }

    public string NAME_ { get; set; }

    public string KEY_ { get; set; }

    public int VERSION_ { get; set; }

    public string DEPLOYMENT_ID_ { get; set; }

    public string RESOURCE_NAME_ { get; set; }

    public string DGRM_RESOURCE_NAME_ { get; set; }

    public string DESCRIPTION_ { get; set; }

    public byte? HAS_START_FORM_KEY_ { get; set; }

    public byte? HAS_GRAPHICAL_NOTATION_ { get; set; }

    public byte? SUSPENSION_STATE_ { get; set; }

    public string TENANT_ID_ { get; set; }

    public string DERIVED_FROM_ { get; set; }

    public string DERIVED_FROM_ROOT_ { get; set; }

    public int DERIVED_VERSION_ { get; set; }

    public string ENGINE_VERSION_ { get; set; }

    public virtual ACT_PROCDEF_INFO ACT_PROCDEF_INFO { get; set; }

    public virtual ICollection<ACT_RU_DEADLETTER_JOB> ACT_RU_DEADLETTER_JOBs { get; set; } = new List<ACT_RU_DEADLETTER_JOB>();

    public virtual ICollection<ACT_RU_EXECUTION> ACT_RU_EXECUTIONs { get; set; } = new List<ACT_RU_EXECUTION>();

    public virtual ICollection<ACT_RU_IDENTITYLINK> ACT_RU_IDENTITYLINKs { get; set; } = new List<ACT_RU_IDENTITYLINK>();

    public virtual ICollection<ACT_RU_JOB> ACT_RU_JOBs { get; set; } = new List<ACT_RU_JOB>();

    public virtual ICollection<ACT_RU_SUSPENDED_JOB> ACT_RU_SUSPENDED_JOBs { get; set; } = new List<ACT_RU_SUSPENDED_JOB>();

    public virtual ICollection<ACT_RU_TASK> ACT_RU_TASKs { get; set; } = new List<ACT_RU_TASK>();

    public virtual ICollection<ACT_RU_TIMER_JOB> ACT_RU_TIMER_JOBs { get; set; } = new List<ACT_RU_TIMER_JOB>();
}