// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ACT_RU_VARIABLE
{
    public string ID_ { get; set; }

    public int? REV_ { get; set; }

    public string TYPE_ { get; set; }

    public string NAME_ { get; set; }

    public string EXECUTION_ID_ { get; set; }

    public string PROC_INST_ID_ { get; set; }

    public string TASK_ID_ { get; set; }

    public string SCOPE_ID_ { get; set; }

    public string SUB_SCOPE_ID_ { get; set; }

    public string SCOPE_TYPE_ { get; set; }

    public string BYTEARRAY_ID_ { get; set; }

    public double? DOUBLE_ { get; set; }

    public decimal? LONG_ { get; set; }

    public string TEXT_ { get; set; }

    public string TEXT2_ { get; set; }

    public virtual ACT_GE_BYTEARRAY BYTEARRAY_ID_Navigation { get; set; }

    public virtual ACT_RU_EXECUTION EXECUTION_ID_Navigation { get; set; }

    public virtual ACT_RU_EXECUTION PROC_INST_ID_Navigation { get; set; }
}