// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ACT_ID_PRIV_MAPPING
{
    public string ID_ { get; set; }

    public string PRIV_ID_ { get; set; }

    public string USER_ID_ { get; set; }

    public string GROUP_ID_ { get; set; }

    public virtual ACT_ID_PRIV PRIV_ID_Navigation { get; set; }
}