// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ACT_RU_ACTINST
{
    public string ID_ { get; set; }

    public int? REV_ { get; set; }

    public string PROC_DEF_ID_ { get; set; }

    public string PROC_INST_ID_ { get; set; }

    public string EXECUTION_ID_ { get; set; }

    public string ACT_ID_ { get; set; }

    public string TASK_ID_ { get; set; }

    public string CALL_PROC_INST_ID_ { get; set; }

    public string ACT_NAME_ { get; set; }

    public string ACT_TYPE_ { get; set; }

    public string ASSIGNEE_ { get; set; }

    public DateTime START_TIME_ { get; set; }

    public DateTime? END_TIME_ { get; set; }

    public decimal? DURATION_ { get; set; }

    public int? TRANSACTION_ORDER_ { get; set; }

    public string DELETE_REASON_ { get; set; }

    public string TENANT_ID_ { get; set; }
}