// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ACT_HI_ATTACHMENT
{
    public string ID_ { get; set; }

    public int? REV_ { get; set; }

    public string USER_ID_ { get; set; }

    public string NAME_ { get; set; }

    public string DESCRIPTION_ { get; set; }

    public string TYPE_ { get; set; }

    public string TASK_ID_ { get; set; }

    public string PROC_INST_ID_ { get; set; }

    public string URL_ { get; set; }

    public string CONTENT_ID_ { get; set; }

    public DateTime? TIME_ { get; set; }
}