// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ACT_HI_IDENTITYLINK
{
    public string ID_ { get; set; }

    public string GROUP_ID_ { get; set; }

    public string TYPE_ { get; set; }

    public string USER_ID_ { get; set; }

    public string TASK_ID_ { get; set; }

    public DateTime? CREATE_TIME_ { get; set; }

    public string PROC_INST_ID_ { get; set; }

    public string SCOPE_ID_ { get; set; }

    public string SUB_SCOPE_ID_ { get; set; }

    public string SCOPE_TYPE_ { get; set; }

    public string SCOPE_DEFINITION_ID_ { get; set; }
}