// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ACT_ID_TOKEN
{
    public string ID_ { get; set; }

    public int? REV_ { get; set; }

    public string TOKEN_VALUE_ { get; set; }

    public DateTime? TOKEN_DATE_ { get; set; }

    public string IP_ADDRESS_ { get; set; }

    public string USER_AGENT_ { get; set; }

    public string USER_ID_ { get; set; }

    public string TOKEN_DATA_ { get; set; }
}