// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ACT_ID_BYTEARRAY
{
    public string ID_ { get; set; }

    public int? REV_ { get; set; }

    public string NAME_ { get; set; }

    public byte[] BYTES_ { get; set; }
}