// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ACT_RU_HISTORY_JOB
{
    public string ID_ { get; set; }

    public int? REV_ { get; set; }

    public DateTime? LOCK_EXP_TIME_ { get; set; }

    public string LOCK_OWNER_ { get; set; }

    public int? RETRIES_ { get; set; }

    public string EXCEPTION_STACK_ID_ { get; set; }

    public string EXCEPTION_MSG_ { get; set; }

    public string HANDLER_TYPE_ { get; set; }

    public string HANDLER_CFG_ { get; set; }

    public string CUSTOM_VALUES_ID_ { get; set; }

    public string ADV_HANDLER_CFG_ID_ { get; set; }

    public DateTime? CREATE_TIME_ { get; set; }

    public string SCOPE_TYPE_ { get; set; }

    public string TENANT_ID_ { get; set; }
}