// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ACT_HI_COMMENT
{
    public string ID_ { get; set; }

    public string TYPE_ { get; set; }

    public DateTime TIME_ { get; set; }

    public string USER_ID_ { get; set; }

    public string TASK_ID_ { get; set; }

    public string PROC_INST_ID_ { get; set; }

    public string ACTION_ { get; set; }

    public string MESSAGE_ { get; set; }

    public byte[] FULL_MSG_ { get; set; }
}