// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ACT_ID_INFO
{
    public string ID_ { get; set; }

    public int? REV_ { get; set; }

    public string USER_ID_ { get; set; }

    public string TYPE_ { get; set; }

    public string KEY_ { get; set; }

    public string VALUE_ { get; set; }

    public byte[] PASSWORD_ { get; set; }

    public string PARENT_ID_ { get; set; }
}