// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ACT_EVT_LOG
{
    public decimal LOG_NR_ { get; set; }

    public string TYPE_ { get; set; }

    public string PROC_DEF_ID_ { get; set; }

    public string PROC_INST_ID_ { get; set; }

    public string EXECUTION_ID_ { get; set; }

    public string TASK_ID_ { get; set; }

    public DateTime TIME_STAMP_ { get; set; }

    public string USER_ID_ { get; set; }

    public byte[] DATA_ { get; set; }

    public string LOCK_OWNER_ { get; set; }

    public DateTime? LOCK_TIME_ { get; set; }

    public byte? IS_PROCESSED_ { get; set; }
}