// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class adms_devcmd
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string app_name { get; set; }

    public long? cmd_id { get; set; }

    public short? comm_type { get; set; }

    public DateTime commit_time { get; set; }

    public string content { get; set; }

    public bool? is_imme { get; set; }

    public string remark { get; set; }

    public DateTime? return_time { get; set; }

    public int? return_value { get; set; }

    public string sn { get; set; }

    public bool? sync { get; set; }
}