// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class adms_acc_device_log
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string card_no { get; set; }

    public string event_addr { get; set; }

    public string event_desc { get; set; }

    public string event_no { get; set; }

    public string event_time { get; set; }

    public string inout_status { get; set; }

    public string log_index { get; set; }

    public string open_mode { get; set; }

    public string pin { get; set; }

    public string sn { get; set; }

    public string verify_type { get; set; }
}