// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class att_day_card_detail
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string att_date { get; set; }

    public string att_times { get; set; }

    public int? card_count { get; set; }

    public string auth_dept_code { get; set; }

    public string auth_dept_id { get; set; }

    public string auth_dept_name { get; set; }

    public string earliest_time { get; set; }

    public string latest_time { get; set; }

    public string pers_person_lastname { get; set; }

    public string pers_person_name { get; set; }

    public string pers_person_pin { get; set; }
}