// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class att_transaction
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string auth_area_id { get; set; }

    public string auth_area_name { get; set; }

    public string auth_area_no { get; set; }

    public string att_date { get; set; }

    public DateTime? att_datetime { get; set; }

    public string att_photo_url { get; set; }

    public string att_place { get; set; }

    public string att_state { get; set; }

    public string att_time { get; set; }

    public string att_verify { get; set; }

    public string auth_dept_code { get; set; }

    public string auth_dept_id { get; set; }

    public string auth_dept_name { get; set; }

    public string device_id { get; set; }

    public string device_name { get; set; }

    public string device_sn { get; set; }

    public short? door_no { get; set; }

    public string latitude { get; set; }

    public string longitude { get; set; }

    public string mark { get; set; }

    public string mask_flag { get; set; }

    public string pers_person_last_name { get; set; }

    public string pers_person_name { get; set; }

    public string pers_person_pin { get; set; }

    public string temperature { get; set; }
}