// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class att_shift
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public short? attendance_mode { get; set; }

    public bool? is_shift_within_month { get; set; }

    public short? overtime_mode { get; set; }

    public short? overtime_sign { get; set; }

    public short? period_number { get; set; }

    public string period_start_mode { get; set; }

    public short? periodic_unit { get; set; }

    public string shift_color { get; set; }

    public string shift_name { get; set; }

    public string shift_no { get; set; }

    public short? shift_type { get; set; }

    public DateTime? start_date { get; set; }

    public string time_slot_detail_ids { get; set; }

    public string shift_worktype { get; set; }

    public virtual ICollection<att_cyclesch> cyclesches { get; set; } = new List<att_cyclesch>();

    public virtual ICollection<att_deptsch> deptsches { get; set; } = new List<att_deptsch>();

    public virtual ICollection<att_groupsch> groupsches { get; set; } = new List<att_groupsch>();

    public virtual ICollection<att_personsch> personsches { get; set; } = new List<att_personsch>();

    public virtual ICollection<att_timeslot> timeslots { get; set; } = new List<att_timeslot>();
}