// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class att_custom_rule
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string count_overtime { get; set; }

    public string cross_day { get; set; }

    public string late_and_early { get; set; }

    public string maxovertime_minutes { get; set; }

    public string maxovertime_type { get; set; }

    public string rule_name { get; set; }

    public string rule_type { get; set; }

    public string shortest_overtime_minutes { get; set; }

    public string sign_break_time { get; set; }

    public string sign_in { get; set; }

    public string sign_out { get; set; }

    public string smart_find_class { get; set; }
}