// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class att_personsch
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public DateTime? end_date { get; set; }

    public string pers_person_id { get; set; }

    public string schedule_id { get; set; }

    public short? schedule_type { get; set; }

    public DateTime? start_date { get; set; }

    public virtual ICollection<att_shift> shifts { get; set; } = new List<att_shift>();
}