// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class att_sign
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string after_sign_record { get; set; }

    public string att_state { get; set; }

    public string before_sign_record { get; set; }

    public string business_key { get; set; }

    public string auth_dept_id { get; set; }

    public string flow_status { get; set; }

    public string pers_person_id { get; set; }

    public string pers_person_pin { get; set; }

    public string remark { get; set; }

    public DateTime? sign_datetime { get; set; }
}