// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class att_autoexport
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string auth_area_id { get; set; }

    public string auth_dept_id { get; set; }

    public string email_content { get; set; }

    public string email_recipients { get; set; }

    public string email_subject { get; set; }

    public string email_type { get; set; }

    public string file_content_format { get; set; }

    public string file_date_format { get; set; }

    public string file_field_convert { get; set; }

    public string file_name { get; set; }

    public string file_time_format { get; set; }

    public string file_type { get; set; }

    public string filter_dept_ids { get; set; }

    public string ftp_password { get; set; }

    public int? ftp_port { get; set; }

    public string ftp_url { get; set; }

    public string ftp_username { get; set; }

    public string job_class { get; set; }

    public string job_cron { get; set; }

    public string job_name { get; set; }

    public string job_status { get; set; }

    public string report_type { get; set; }

    public string send_format { get; set; }

    public string time_send_frequency { get; set; }

    public string time_send_interval { get; set; }
}