// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class auth_api_log
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string client_token { get; set; }

    public int? cost_time { get; set; }

    public DateTime? end_time { get; set; }

    public string request_ip { get; set; }

    public string request_params { get; set; }

    public string request_result { get; set; }

    public string request_url { get; set; }

    public DateTime? start_time { get; set; }
}