// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class auth_company
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string admin_name { get; set; }

    public string admin_pwd { get; set; }

    public int? att_distance { get; set; }

    public string company_address { get; set; }

    public string company_name { get; set; }

    public string contact_name { get; set; }

    public string email { get; set; }

    public string latitude { get; set; }

    public string longitude { get; set; }

    public string status { get; set; }

    public string telephone { get; set; }
}