// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class auth_user
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string email { get; set; }

    public bool? init_flag { get; set; }

    public bool? is_active { get; set; }

    public bool? is_audit { get; set; }

    public bool? is_staff { get; set; }

    public bool? is_superuser { get; set; }

    public string last_name { get; set; }

    public string login_pwd { get; set; }

    public string name { get; set; }

    public string phone { get; set; }

    public DateTime? pwd_create_time { get; set; }

    public string pwd_init_flag { get; set; }

    public string salt { get; set; }

    public int? user_login_limit { get; set; }

    public string user_type { get; set; }

    public string username { get; set; }

    public virtual ICollection<auth_biotemplate> auth_biotemplates { get; set; } = new List<auth_biotemplate>();

    public virtual ICollection<auth_area> auth_areas { get; set; } = new List<auth_area>();

    public virtual ICollection<auth_board> auth_boards { get; set; } = new List<auth_board>();

    public virtual ICollection<auth_department> auth_depts { get; set; } = new List<auth_department>();

    public virtual ICollection<auth_role> auth_roles { get; set; } = new List<auth_role>();
}