// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class auth_permission
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string action_link { get; set; }

    public string available { get; set; }

    public string code { get; set; }

    public string img { get; set; }

    public string img_hover { get; set; }

    public string name { get; set; }

    public int? order_no { get; set; }

    public string permission { get; set; }

    public string resource_type { get; set; }

    public string auth_permission_parent_id { get; set; }

    public virtual ICollection<auth_permission> Inverseauth_permission_parent { get; set; } = new List<auth_permission>();

    public virtual auth_permission auth_permission_parent { get; set; }

    public virtual ICollection<auth_role> auth_roles { get; set; } = new List<auth_role>();
}