// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class base_print_template
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string code { get; set; }

    public int? height { get; set; }

    public bool? init_flag { get; set; }

    public string module_code { get; set; }

    public string name { get; set; }

    public short? orientation { get; set; }

    public int? width { get; set; }

    public virtual ICollection<base_print_param> base_print_params { get; set; } = new List<base_print_param>();
}