// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class data_source
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string db_name { get; set; }

    public string ip { get; set; }

    public string password { get; set; }

    public string port { get; set; }

    public string soft_version { get; set; }

    public string type { get; set; }

    public string username { get; set; }
}