// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class device_info
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string area_id { get; set; }

    public string area_name { get; set; }

    public string device_alias { get; set; }

    public string device_ip { get; set; }

    public string device_model_name { get; set; }

    public string device_name { get; set; }

    public string device_port { get; set; }

    public string device_sn { get; set; }

    public string device_version { get; set; }

    public string parent_device_id { get; set; }

    public string reserve { get; set; }

    public string source_module { get; set; }

    public string status { get; set; }
}