// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class event_record
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string area_id { get; set; }

    public string area_name { get; set; }

    public string business_id { get; set; }

    public string capture_img_url { get; set; }

    public string level_name { get; set; }

    public string level_val { get; set; }

    public string event_name { get; set; }

    public string event_name_key { get; set; }

    public string event_remark { get; set; }

    public DateTime? event_time { get; set; }

    public string type_code { get; set; }

    public string event_type_id { get; set; }

    public string face_rate { get; set; }

    public short? inout_status { get; set; }

    public string level_val_color { get; set; }

    public string obj_key { get; set; }

    public string obj_name { get; set; }

    public string obj_type { get; set; }

    public string panorama_img_url { get; set; }

    public string path { get; set; }

    public string process_state { get; set; }

    public string re_id { get; set; }

    public string source_key { get; set; }

    public string source_module { get; set; }

    public string source_name { get; set; }

    public string video_channel_id { get; set; }
}