// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class FLW_EV_DATABASECHANGELOGLOCK
{
    public int ID { get; set; }

    public bool LOCKED { get; set; }

    public DateTime? LOCKGRANTED { get; set; }

    public string LOCKEDBY { get; set; }
}