// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class FLW_EVENT_RESOURCE
{
    public string ID_ { get; set; }

    public string NAME_ { get; set; }

    public string DEPLOYMENT_ID_ { get; set; }

    public byte[] RESOURCE_BYTES_ { get; set; }
}