// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class FLW_RU_BATCH
{
    public string ID_ { get; set; }

    public int? REV_ { get; set; }

    public string TYPE_ { get; set; }

    public string SEARCH_KEY_ { get; set; }

    public string SEARCH_KEY2_ { get; set; }

    public DateTime CREATE_TIME_ { get; set; }

    public DateTime? COMPLETE_TIME_ { get; set; }

    public string STATUS_ { get; set; }

    public string BATCH_DOC_ID_ { get; set; }

    public string TENANT_ID_ { get; set; }

    public virtual ICollection<FLW_RU_BATCH_PART> FLW_RU_BATCH_PARTs { get; set; } = new List<FLW_RU_BATCH_PART>();
}