// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class FLW_EVENT_DEPLOYMENT
{
    public string ID_ { get; set; }

    public string NAME_ { get; set; }

    public string CATEGORY_ { get; set; }

    public DateTime? DEPLOY_TIME_ { get; set; }

    public string TENANT_ID_ { get; set; }

    public string PARENT_DEPLOYMENT_ID_ { get; set; }
}