// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ias_event
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string area_id { get; set; }

    public string area_name { get; set; }

    public string device_id { get; set; }

    public string device_ip { get; set; }

    public string device_name { get; set; }

    public string event_cid { get; set; }

    public string event_content { get; set; }

    public int? event_hash_code { get; set; }

    public string event_name { get; set; }

    public string event_point_type { get; set; }

    public DateTime? event_time { get; set; }

    public short? event_type { get; set; }

    public int? partition_code { get; set; }

    public string partition_name { get; set; }

    public string point_code { get; set; }

    public string point_name { get; set; }
}