// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class ias_partition
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string area_id { get; set; }

    public int? code { get; set; }

    public string device_id { get; set; }

    public string name { get; set; }

    public string remark { get; set; }

    public string type { get; set; }

    public virtual ICollection<ias_partition_sched> ias_partition_scheds { get; set; } = new List<ias_partition_sched>();
}