// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class intg_base_server
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string base_account { get; set; }

    public string base_db_ip { get; set; }

    public string base_db_name { get; set; }

    public int? base_db_port { get; set; }

    public string base_db_type { get; set; }

    public string base_enable { get; set; }

    public string base_encryption { get; set; }

    public string base_iv { get; set; }

    public string base_key { get; set; }

    public string base_pwd { get; set; }

    public string base_queue { get; set; }

    public string base_task_type { get; set; }

    public string base_token { get; set; }

    public string base_topic { get; set; }

    public string base_url { get; set; }

    public string integrate_format { get; set; }

    public string name { get; set; }

    public string server_id { get; set; }
}