// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class intg_business_log
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string business_action { get; set; }

    public string data_content { get; set; }

    public string exception { get; set; }

    public int? exception_time { get; set; }

    public string integrate_format { get; set; }

    public string mid_data_id { get; set; }

    public string obj_type { get; set; }

    public string op_type { get; set; }

    public string result_code { get; set; }

    public string result_msg { get; set; }

    public string server_id { get; set; }

    public string server_name { get; set; }

    public int? sync_time { get; set; }

    public string task_type { get; set; }
}