// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class map_element
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public int? border_width { get; set; }

    public string color { get; set; }

    public string entity_id { get; set; }

    public string entity_type { get; set; }

    public string icon_type { get; set; }

    public string rotation_angle { get; set; }

    public double? width { get; set; }

    public string map_id { get; set; }

    public virtual map_map map { get; set; }

    public virtual ICollection<map_element_po> map_element_pos { get; set; } = new List<map_element_po>();
}