// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class message_record
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string business_id { get; set; }

    public string business_type { get; set; }

    public string content { get; set; }

    public string display_mode { get; set; }

    public string ext_data { get; set; }

    public string href { get; set; }

    public string msg_type { get; set; }

    public string receiver_id { get; set; }

    public string receiver_obj { get; set; }

    public string source_module { get; set; }

    public string title { get; set; }

    public virtual ICollection<message_record_receiver> message_record_receivers { get; set; } = new List<message_record_receiver>();
}