// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class mid_datum
{
    public long ids { get; set; }

    public DateTime? create_time { get; set; }

    public string data_content { get; set; }

    public string obj_type { get; set; }

    public string op_result { get; set; }

    public string op_type { get; set; }
}