// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class patrol_total
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public short? absence_patrol_times { get; set; }

    public string card_no { get; set; }

    public short? lack_patrol_times { get; set; }

    public string name { get; set; }

    public string patrol_persons { get; set; }

    public string pin { get; set; }

    public string plan_name { get; set; }

    public short? real_patrol_times { get; set; }

    public string route_name { get; set; }

    public short? should_patrol_times { get; set; }

    public short? timeout_times { get; set; }

    public DateTime? total_date { get; set; }

    public short? total_type { get; set; }

    public short? wrong_patrol_times { get; set; }
}