// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class patrol_plan
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public short? cycle_type { get; set; }

    public DateTime? end_date { get; set; }

    public short? month_end_date { get; set; }

    public short? month_mode { get; set; }

    public string month_plan { get; set; }

    public short? month_start_date { get; set; }

    public string name { get; set; }

    public DateTime? start_date { get; set; }

    public string week_plan { get; set; }

    public virtual ICollection<patrol_route> patrol_routes { get; set; } = new List<patrol_route>();

    public virtual ICollection<patrol_shift> patrol_shifts { get; set; } = new List<patrol_shift>();
}