// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class patrol_point
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string acc_reader_id { get; set; }

    public int? level_id { get; set; }

    public string level_name { get; set; }

    public string name { get; set; }

    public string patrol_tag { get; set; }

    public string patrol_tag_name { get; set; }

    public string position { get; set; }

    public string patrol_device_id { get; set; }

    public virtual patrol_device patrol_device { get; set; }

    public virtual ICollection<patrol_route_point> patrol_route_points { get; set; } = new List<patrol_route_point>();
}