// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class pers_biotemplate
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public short? bio_type { get; set; }

    public bool? duress { get; set; }

    public string person_id { get; set; }

    public string person_pin { get; set; }

    public string template { get; set; }

    public short? template_no { get; set; }

    public short? template_no_index { get; set; }

    public short? valid_type { get; set; }

    public string version { get; set; }

    public virtual pers_person person { get; set; }
}