// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class pers_personnallist_person
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string email { get; set; }

    public string id_card { get; set; }

    public string last_name { get; set; }

    public string link_tbl { get; set; }

    public string mobile_phone { get; set; }

    public DateTime? person_birthday { get; set; }

    public string person_gender { get; set; }

    public string person_id { get; set; }

    public string person_name { get; set; }

    public string person_pin { get; set; }

    public string personnallist_id { get; set; }

    public string position_name { get; set; }
}