// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class pers_identity_card_info
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string address { get; set; }

    public DateTime? birthday { get; set; }

    public DateTime? end_date { get; set; }

    public string gender { get; set; }

    public string id_card { get; set; }

    public string issued_organ { get; set; }

    public string name { get; set; }

    public string nation { get; set; }

    public string photo_path { get; set; }

    public string physical_no { get; set; }

    public DateTime? start_date { get; set; }

    public string template1 { get; set; }

    public string template2 { get; set; }
}