// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class pers_temp_person
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string acc_level_ids { get; set; }

    public DateTime? birthday { get; set; }

    public string card_nos { get; set; }

    public string cert_number { get; set; }

    public string cert_type { get; set; }

    public string company_name { get; set; }

    public string crop_photo_path { get; set; }

    public string auth_dept_id { get; set; }

    public string device_pwd { get; set; }

    public string email { get; set; }

    public bool? exists_mobile_user { get; set; }

    public string family_address { get; set; }

    public string gender { get; set; }

    public DateTime? hire_date { get; set; }

    public string is_from { get; set; }

    public string last_name { get; set; }

    public string mobile_phone { get; set; }

    public string name { get; set; }

    public string person_pwd { get; set; }

    public string photo_path { get; set; }

    public string pin { get; set; }

    public string position_code { get; set; }

    public short? status { get; set; }
}