// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class pers_wiegandfmt
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public long? business_id { get; set; }

    public string card_fmt { get; set; }

    public bool? init_flag { get; set; }

    public bool? is_default_fmt { get; set; }

    public string name { get; set; }

    public string parity_fmt { get; set; }

    public string site_code { get; set; }

    public short wiegand_count { get; set; }

    public short? wiegand_mode { get; set; }
}