// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class pers_card
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string bussiness_id { get; set; }

    public string card_no { get; set; }

    public short? card_op_type { get; set; }

    public short card_state { get; set; }

    public short card_type { get; set; }

    public DateTime? end_time { get; set; }

    public string is_from { get; set; }

    public DateTime issue_time { get; set; }

    public string logical_card_no { get; set; }

    public string person_id { get; set; }

    public string person_pin { get; set; }

    public DateTime? start_time { get; set; }
}