// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class pers_person
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public bool? app_authorization { get; set; }

    public DateTime? birthday { get; set; }

    public string car_plate { get; set; }

    public string auth_dept_id { get; set; }

    public string email { get; set; }

    public bool? enabled_credential { get; set; }

    public short? exception_flag { get; set; }

    public bool? exists_mobile_user { get; set; }

    public string gender { get; set; }

    public DateTime? hire_date { get; set; }

    public string id_card { get; set; }

    public string id_card_physical_no { get; set; }

    public string is_from { get; set; }

    public bool? is_sendmail { get; set; }

    public string last_name { get; set; }

    public string mobile_phone { get; set; }

    public string name { get; set; }

    public string name_spell { get; set; }

    public long? number_pin { get; set; }

    public int? pers_login_limit { get; set; }

    public string person_pwd { get; set; }

    public short? person_type { get; set; }

    public string photo_path { get; set; }

    public string pin { get; set; }

    public bool? pin_letter { get; set; }

    public string self_pwd { get; set; }

    public bool? send_app { get; set; }

    public bool? send_sms { get; set; }

    public bool? send_whatsapp { get; set; }

    public string ssn { get; set; }

    public short? status { get; set; }

    public string whatsapp_mobileno { get; set; }

    public string position_id { get; set; }

    public virtual ICollection<pers_biotemplate> pers_biotemplates { get; set; } = new List<pers_biotemplate>();

    public virtual ICollection<pers_certificate> pers_certificates { get; set; } = new List<pers_certificate>();

    public virtual ICollection<pers_personchange> pers_personchanges { get; set; } = new List<pers_personchange>();

    public virtual pers_position position { get; set; }
}