// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class pos_cardmanage
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public double? balance { get; set; }

    public double? card_cost { get; set; }

    public string card_no { get; set; }

    public int? card_privage { get; set; }

    public string card_pwd { get; set; }

    public int? card_serial_num { get; set; }

    public string card_status { get; set; }

    public string dept_code { get; set; }

    public string dept_id { get; set; }

    public string dept_name { get; set; }

    public int? is_valid { get; set; }

    public DateTime? issue_date { get; set; }

    public double? mng_cost { get; set; }

    public string password { get; set; }

    public string person_id { get; set; }

    public string person_last_name { get; set; }

    public string person_name { get; set; }

    public string person_pin { get; set; }

    public DateTime? pos_date { get; set; }

    public double? subbalance { get; set; }

    public int? sys_card_no { get; set; }

    public string cardkind_id { get; set; }

    public virtual pos_cardkind cardkind { get; set; }

    public virtual ICollection<pos_allowance_card_lock> pos_allowance_card_locks { get; set; } = new List<pos_allowance_card_lock>();

    public virtual ICollection<pos_allowancelogrecord> pos_allowancelogrecords { get; set; } = new List<pos_allowancelogrecord>();
}