// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class pos_transactioncard
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public int? allow_base_batch { get; set; }

    public int? allow_batch { get; set; }

    public int? allow_type { get; set; }

    public double? balance { get; set; }

    public string card { get; set; }

    public int? card_cash_type { get; set; }

    public string card_name { get; set; }

    public int? card_serial { get; set; }

    public DateTime? change_time { get; set; }

    public DateTime? check_time { get; set; }

    public DateTime? convey_time { get; set; }

    public string creat_operator { get; set; }

    public string dept_code { get; set; }

    public string dept_id { get; set; }

    public string dept_name { get; set; }

    public int? discount { get; set; }

    public int? hide_column { get; set; }

    public DateTime? issue_date { get; set; }

    public int? log_flag { get; set; }

    public double? money { get; set; }

    public string person_id { get; set; }

    public string person_last_name { get; set; }

    public string person_name { get; set; }

    public string person_pin { get; set; }

    public int? recharge_type { get; set; }

    public int? record_type { get; set; }

    public int? serial_num { get; set; }

    public string sn_name { get; set; }

    public string status { get; set; }

    public double? subbalance { get; set; }

    public double? submoney { get; set; }

    public int? sys_card_no { get; set; }

    public string unique_key { get; set; }
}