// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class pos_handconsume
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public double? balance { get; set; }

    public string card_no { get; set; }

    public string card_serial_no { get; set; }

    public string card_sys_no { get; set; }

    public DateTime? date_time { get; set; }

    public string dept_code { get; set; }

    public string dept_id { get; set; }

    public string dept_name { get; set; }

    public string device_sn { get; set; }

    public double? money { get; set; }

    public string person_id { get; set; }

    public string person_last_name { get; set; }

    public string person_name { get; set; }

    public string person_pin { get; set; }

    public short? status { get; set; }

    public double? subbalance { get; set; }

    public double? submoney { get; set; }

    public string device_id { get; set; }

    public string meal_id { get; set; }

    public virtual pos_meal meal { get; set; }
}