// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class pos_device
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public int? allow_stamp_id { get; set; }

    public string auth_area_id { get; set; }

    public int? be_parsed_cmd_count { get; set; }

    public int? be_parsed_files_count { get; set; }

    public int? cash_mode { get; set; }

    public int? cash_type { get; set; }

    public short? check_operate { get; set; }

    public short? check_white_list { get; set; }

    public short? consume_fun_type { get; set; }

    public int? consume_mode { get; set; }

    public string dev_alias { get; set; }

    public string device_name { get; set; }

    public int? favorable { get; set; }

    public double? fix_amount { get; set; }

    public int? full_stamp_id { get; set; }

    public string fw_version { get; set; }

    public string ip_address { get; set; }

    public int? ip_port { get; set; }

    public short? is_accouting { get; set; }

    public short? is_add { get; set; }

    public short? is_clear { get; set; }

    public short? is_press_ok { get; set; }

    public bool? is_record_complete { get; set; }

    public DateTime? last_activity_time { get; set; }

    public int? long_time { get; set; }

    public double? max_amount { get; set; }

    public string push_version { get; set; }

    public string sn { get; set; }

    public int? stamp_id { get; set; }

    public bool? state { get; set; }

    public double? time_price { get; set; }

    public int? use_type { get; set; }

    public string dininghall_id { get; set; }

    public virtual pos_dininghall dininghall { get; set; }

    public virtual ICollection<pos_keyvalue_device> pos_keyvalue_devices { get; set; } = new List<pos_keyvalue_device>();

    public virtual ICollection<pos_meal_device> pos_meal_devices { get; set; } = new List<pos_meal_device>();

    public virtual ICollection<pos_splittime_device> pos_splittime_devices { get; set; } = new List<pos_splittime_device>();

    public virtual ICollection<pos_storedetail_device> pos_storedetail_devices { get; set; } = new List<pos_storedetail_device>();
}