// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class pos_allowancelogrecord
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string base_batch { get; set; }

    public string batch { get; set; }

    public double? card_balance { get; set; }

    public string card_no { get; set; }

    public string card_serial_num { get; set; }

    public double? card_subbalance { get; set; }

    public string check_name { get; set; }

    public string dept_code { get; set; }

    public string dept_id { get; set; }

    public string dept_name { get; set; }

    public int? is_check { get; set; }

    public bool? is_clear { get; set; }

    public int? is_receive { get; set; }

    public int? is_transfer { get; set; }

    public int? is_valid { get; set; }

    public double? money { get; set; }

    public string person_id { get; set; }

    public string person_last_name { get; set; }

    public string person_name { get; set; }

    public string person_pin { get; set; }

    public DateTime? receive_date { get; set; }

    public double? receive_money { get; set; }

    public string remark { get; set; }

    public DateTime? start_date { get; set; }

    public int? status { get; set; }

    public DateTime? valid_date { get; set; }

    public string cardmanage_id { get; set; }

    public virtual pos_cardmanage cardmanage { get; set; }
}