// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class pos_cardkind
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string batchtime_id { get; set; }

    public string batchtime_name { get; set; }

    public string code { get; set; }

    public int? date_max_count { get; set; }

    public double? date_max_money { get; set; }

    public int? discount { get; set; }

    public double? less_money { get; set; }

    public double? max_money { get; set; }

    public int? meal_max_count { get; set; }

    public double? meal_max_money { get; set; }

    public string name { get; set; }

    public double? per_max_money { get; set; }

    public string remark { get; set; }

    public int? status { get; set; }

    public int? use_date { get; set; }

    public int? use_fingerprint { get; set; }

    public virtual ICollection<pos_cardkind_device> pos_cardkind_devices { get; set; } = new List<pos_cardkind_device>();

    public virtual ICollection<pos_cardkind_meal> pos_cardkind_meals { get; set; } = new List<pos_cardkind_meal>();

    public virtual ICollection<pos_cardmanage> pos_cardmanages { get; set; } = new List<pos_cardmanage>();
}