// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class psg_gate_passrule
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public long? b_id { get; set; }

    public string friday_end1 { get; set; }

    public string friday_end2 { get; set; }

    public string friday_end3 { get; set; }

    public string friday_end4 { get; set; }

    public string friday_end5 { get; set; }

    public short? friday_opengate_mode1 { get; set; }

    public short? friday_opengate_mode2 { get; set; }

    public short? friday_opengate_mode3 { get; set; }

    public short? friday_opengate_mode4 { get; set; }

    public short? friday_opengate_mode5 { get; set; }

    public string friday_start1 { get; set; }

    public string friday_start2 { get; set; }

    public string friday_start3 { get; set; }

    public string friday_start4 { get; set; }

    public string friday_start5 { get; set; }

    public bool? init_flag { get; set; }

    public string monday_end1 { get; set; }

    public string monday_end2 { get; set; }

    public string monday_end3 { get; set; }

    public string monday_end4 { get; set; }

    public string monday_end5 { get; set; }

    public short? monday_opengate_mode1 { get; set; }

    public short? monday_opengate_mode2 { get; set; }

    public short? monday_opengate_mode3 { get; set; }

    public short? monday_opengate_mode4 { get; set; }

    public short? monday_opengate_mode5 { get; set; }

    public string monday_start1 { get; set; }

    public string monday_start2 { get; set; }

    public string monday_start3 { get; set; }

    public string monday_start4 { get; set; }

    public string monday_start5 { get; set; }

    public string name { get; set; }

    public string remark { get; set; }

    public string saturday_end1 { get; set; }

    public string saturday_end2 { get; set; }

    public string saturday_end3 { get; set; }

    public string saturday_end4 { get; set; }

    public string saturday_end5 { get; set; }

    public short? saturday_opengate_mode1 { get; set; }

    public short? saturday_opengate_mode2 { get; set; }

    public short? saturday_opengate_mode3 { get; set; }

    public short? saturday_opengate_mode4 { get; set; }

    public short? saturday_opengate_mode5 { get; set; }

    public string saturday_start1 { get; set; }

    public string saturday_start2 { get; set; }

    public string saturday_start3 { get; set; }

    public string saturday_start4 { get; set; }

    public string saturday_start5 { get; set; }

    public string sunday_end1 { get; set; }

    public string sunday_end2 { get; set; }

    public string sunday_end3 { get; set; }

    public string sunday_end4 { get; set; }

    public string sunday_end5 { get; set; }

    public short? sunday_opengate_mode1 { get; set; }

    public short? sunday_opengate_mode2 { get; set; }

    public short? sunday_opengate_mode3 { get; set; }

    public short? sunday_opengate_mode4 { get; set; }

    public short? sunday_opengate_mode5 { get; set; }

    public string sunday_start1 { get; set; }

    public string sunday_start2 { get; set; }

    public string sunday_start3 { get; set; }

    public string sunday_start4 { get; set; }

    public string sunday_start5 { get; set; }

    public string thursday_end1 { get; set; }

    public string thursday_end2 { get; set; }

    public string thursday_end3 { get; set; }

    public string thursday_end4 { get; set; }

    public string thursday_end5 { get; set; }

    public short? thursday_opengate_mode1 { get; set; }

    public short? thursday_opengate_mode2 { get; set; }

    public short? thursday_opengate_mode3 { get; set; }

    public short? thursday_opengate_mode4 { get; set; }

    public short? thursday_opengate_mode5 { get; set; }

    public string thursday_start1 { get; set; }

    public string thursday_start2 { get; set; }

    public string thursday_start3 { get; set; }

    public string thursday_start4 { get; set; }

    public string thursday_start5 { get; set; }

    public string tuesday_end1 { get; set; }

    public string tuesday_end2 { get; set; }

    public string tuesday_end3 { get; set; }

    public string tuesday_end4 { get; set; }

    public string tuesday_end5 { get; set; }

    public short? tuesday_opengate_mode1 { get; set; }

    public short? tuesday_opengate_mode2 { get; set; }

    public short? tuesday_opengate_mode3 { get; set; }

    public short? tuesday_opengate_mode4 { get; set; }

    public short? tuesday_opengate_mode5 { get; set; }

    public string tuesday_start1 { get; set; }

    public string tuesday_start2 { get; set; }

    public string tuesday_start3 { get; set; }

    public string tuesday_start4 { get; set; }

    public string tuesday_start5 { get; set; }

    public string wednesday_end1 { get; set; }

    public string wednesday_end2 { get; set; }

    public string wednesday_end3 { get; set; }

    public string wednesday_end4 { get; set; }

    public string wednesday_end5 { get; set; }

    public short? wednesday_opengate_mode1 { get; set; }

    public short? wednesday_opengate_mode2 { get; set; }

    public short? wednesday_opengate_mode3 { get; set; }

    public short? wednesday_opengate_mode4 { get; set; }

    public short? wednesday_opengate_mode5 { get; set; }

    public string wednesday_start1 { get; set; }

    public string wednesday_start2 { get; set; }

    public string wednesday_start3 { get; set; }

    public string wednesday_start4 { get; set; }

    public string wednesday_start5 { get; set; }

    public virtual ICollection<psg_swing_gate> psg_swing_gates { get; set; } = new List<psg_swing_gate>();

    public virtual ICollection<psg_threeroller_gate> psg_threeroller_gates { get; set; } = new List<psg_threeroller_gate>();

    public virtual ICollection<psg_wing_gate> psg_wing_gates { get; set; } = new List<psg_wing_gate>();
}