// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class psg_linkage
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string name { get; set; }

    public string dev_id { get; set; }

    public virtual psg_device dev { get; set; }

    public virtual ICollection<psg_linkage_inout> psg_linkage_inouts { get; set; } = new List<psg_linkage_inout>();

    public virtual ICollection<psg_linkage_medium> psg_linkage_media { get; set; } = new List<psg_linkage_medium>();

    public virtual ICollection<psg_linkage_trigger> psg_linkage_triggers { get; set; } = new List<psg_linkage_trigger>();

    public virtual ICollection<psg_linkage_vid> psg_linkage_vids { get; set; } = new List<psg_linkage_vid>();
}