// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class psg_transaction
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string area_name { get; set; }

    public string card_no { get; set; }

    public string dept_code { get; set; }

    public string dept_name { get; set; }

    public string description { get; set; }

    public string dev_alias { get; set; }

    public string dev_id { get; set; }

    public string dev_sn { get; set; }

    public short? event_addr { get; set; }

    public string event_name { get; set; }

    public short event_no { get; set; }

    public string event_point_id { get; set; }

    public string event_point_name { get; set; }

    public short? event_point_type { get; set; }

    public DateTime event_time { get; set; }

    public short? gate_type { get; set; }

    public string last_name { get; set; }

    public int? log_id { get; set; }

    public string name { get; set; }

    public string passage_name { get; set; }

    public string pin { get; set; }

    public string reader_name { get; set; }

    public short? reader_state { get; set; }

    public short? trigger_cond { get; set; }

    public string unique_key { get; set; }

    public string verify_mode_name { get; set; }

    public short? verify_mode_no { get; set; }

    public string vid_linkage_handle { get; set; }
}