// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class psg_swing_gate
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string auth_area_id { get; set; }

    public string brake_angle { get; set; }

    public short? close_gate_speed { get; set; }

    public string delay_closegate_time { get; set; }

    public short? direct_intrusion { get; set; }

    public bool? in_channel_verification { get; set; }

    public short? infrared_antipinch_area { get; set; }

    public bool? memory_opening { get; set; }

    public string name { get; set; }

    public short? open_gate_speed { get; set; }

    public string reset_counter { get; set; }

    public short? trailing_entry { get; set; }

    public string unmaned_time { get; set; }

    public string volume { get; set; }

    public string dev_id { get; set; }

    public string gate_pass_rule_id { get; set; }

    public virtual psg_device dev { get; set; }

    public virtual psg_gate_passrule gate_pass_rule { get; set; }
}