// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class psg_gate
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public bool? enabled { get; set; }

    public string force_pwd { get; set; }

    public short gate_no { get; set; }

    public bool? is_disable_audio { get; set; }

    public string name { get; set; }

    public short? reader_type { get; set; }

    public string supper_pwd { get; set; }

    public short verify_mode { get; set; }

    public string dev_id { get; set; }

    public virtual psg_device dev { get; set; }

    public virtual ICollection<psg_level_gate> psg_level_gates { get; set; } = new List<psg_level_gate>();

    public virtual ICollection<psg_reader> psg_readers { get; set; } = new List<psg_reader>();
}