// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class sc_mustering_report
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string area_name { get; set; }

    public string dept_code { get; set; }

    public string dept_name { get; set; }

    public DateTime? enter_time { get; set; }

    public string last_name { get; set; }

    public string mobile_phone { get; set; }

    public string muster_point_id { get; set; }

    public string muster_point_name { get; set; }

    public string name { get; set; }

    public string person_pin { get; set; }

    public string photo_path { get; set; }

    public string sign_point_name { get; set; }

    public string status { get; set; }
}