// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class scene_target_count_area
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public int? area_capacity { get; set; }

    public string channel_codes { get; set; }

    public string edge_device_id { get; set; }

    public string name { get; set; }

    public DateTime? reset_time { get; set; }
}