// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class seq_mid_datum
{
    public long? next_val { get; set; }
}