// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class space_reservation
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string apply_person_dept_name { get; set; }

    public string apply_person_email { get; set; }

    public string apply_person_id { get; set; }

    public string apply_person_lastname { get; set; }

    public string apply_person_name { get; set; }

    public string apply_person_pin { get; set; }

    public string business_id { get; set; }

    public string content { get; set; }

    public DateTime? end_time { get; set; }

    public string microsoft365_web_link { get; set; }

    public string operator_id { get; set; }

    public string remind_time { get; set; }

    public short? reservation_status { get; set; }

    public string space_id { get; set; }

    public short? start_sign_in_time { get; set; }

    public DateTime? start_time { get; set; }

    public string subject { get; set; }

    public string zoom_id { get; set; }

    public string zoom_meeting_id { get; set; }
}