// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class space_transaction
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string apply_person_dept_name { get; set; }

    public string apply_person_name { get; set; }

    public string auth_area_name { get; set; }

    public string auth_dept_code { get; set; }

    public string auth_dept_name { get; set; }

    public short? category { get; set; }

    public string device_name { get; set; }

    public string device_sn { get; set; }

    public DateTime? event_time { get; set; }

    public string log_id { get; set; }

    public string meet_code { get; set; }

    public string meet_room_code { get; set; }

    public string person_last_name { get; set; }

    public string person_name { get; set; }

    public string person_pin { get; set; }

    public short? record_type { get; set; }

    public DateTime? reservation_end_time { get; set; }

    public DateTime? reservation_start_time { get; set; }

    public string space_id { get; set; }

    public string space_name { get; set; }

    public short? status { get; set; }

    public string subject { get; set; }

    public string verify_mode_name { get; set; }

    public int? verify_mode_no { get; set; }
}