// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class space
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string address { get; set; }

    public string auth_area_id { get; set; }

    public int? capacity { get; set; }

    public string disable_reason { get; set; }

    public string email { get; set; }

    public string name { get; set; }

    public string person_id { get; set; }

    public string person_pin { get; set; }

    public string person_tel { get; set; }

    public string picture_path { get; set; }

    public string remark { get; set; }

    public int? retention_time { get; set; }

    public bool? smart_space { get; set; }

    public short? status { get; set; }

    public string zoom_id { get; set; }
}