// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class space_service_transaction
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string apply_person_name { get; set; }

    public DateTime? end_time { get; set; }

    public string remark { get; set; }

    public string service_name { get; set; }

    public string space_name { get; set; }

    public string space_person_name { get; set; }

    public string space_person_pin { get; set; }

    public DateTime? start_time { get; set; }

    public string status { get; set; }

    public string subject { get; set; }
}