// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class vis_linkage
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public bool enabled { get; set; }

    public short event_type { get; set; }

    public string name { get; set; }

    public virtual ICollection<vis_place_linkage> vis_place_linkages { get; set; } = new List<vis_place_linkage>();

    public virtual ICollection<vis_template_linkage> vis_template_linkages { get; set; } = new List<vis_template_linkage>();
}