// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class vis_reservation
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string area_name { get; set; }

    public DateTime? audit_date { get; set; }

    public string audit_remark { get; set; }

    public short? audit_status { get; set; }

    public DateTime? audit_time { get; set; }

    public string business_key { get; set; }

    public string card_no { get; set; }

    public string carried_goods_in { get; set; }

    public string carried_goods_out { get; set; }

    public string cert_photo { get; set; }

    public string change_operator { get; set; }

    public DateTime? change_time { get; set; }

    public DateTime? confirm_date { get; set; }

    public string crop_photo_path { get; set; }

    public string crop_photo_path_file_id { get; set; }

    public string enter_goods_photo { get; set; }

    public string enter_photo { get; set; }

    public string enter_place { get; set; }

    public DateTime? exit_time { get; set; }

    public string is_from { get; set; }

    public string is_visited { get; set; }

    public string level_ids { get; set; }

    public string is_multi_visit { get; set; }

    public string parent_reservation_id { get; set; }

    public string person_pwd { get; set; }

    public string photo_path { get; set; }

    public string photo_path_file_id { get; set; }

    public string receive_wxmini_msg { get; set; }

    public string remark { get; set; }

    public string reservation_type { get; set; }

    public string vis_transaction_id { get; set; }

    public DateTime? visit_date { get; set; }

    public string visit_emp_dept_id { get; set; }

    public string visit_emp_dept_name { get; set; }

    public string visit_emp_id { get; set; }

    public string visit_emp_last_name { get; set; }

    public string visit_emp_name { get; set; }

    public string visit_emp_phone { get; set; }

    public string visit_emp_pin { get; set; }

    public DateTime? visit_end_date { get; set; }

    public string visit_number { get; set; }

    public string visit_reason { get; set; }

    public int? visitor_count { get; set; }

    public string wx_openid { get; set; }

    public string wx_original_id { get; set; }

    public string visitor_id { get; set; }

    public virtual vis_visitor visitor { get; set; }
}