// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class vis_visitor_common_level
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string vis_common_level_id { get; set; }

    public string vis_rese_tran_id { get; set; }

    public string vis_type { get; set; }

    public string visitor_card_no { get; set; }

    public string visitor_id { get; set; }

    public string visitor_last_name { get; set; }

    public string visitor_name { get; set; }

    public string visitor_pin { get; set; }
}