// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class vis_level
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string change_operator { get; set; }

    public DateTime? change_time { get; set; }

    public string level_module { get; set; }

    public string level_name { get; set; }

    public string module_id { get; set; }

    public virtual ICollection<vis_place_level> vis_place_levels { get; set; } = new List<vis_place_level>();

    public virtual ICollection<vis_visiteddepartment_level> vis_visiteddepartment_levels { get; set; } = new List<vis_visiteddepartment_level>();

    public virtual ICollection<vis_visitedperson_level> vis_visitedperson_levels { get; set; } = new List<vis_visitedperson_level>();

    public virtual ICollection<vis_visitor_level> vis_visitor_levels { get; set; } = new List<vis_visitor_level>();
}