// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class vis_visitor
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string car_plate { get; set; }

    public string cert_number { get; set; }

    public string cert_photo { get; set; }

    public string cert_type { get; set; }

    public string change_operator { get; set; }

    public DateTime? change_time { get; set; }

    public string company { get; set; }

    public string email { get; set; }

    public bool? enabled { get; set; }

    public string gender { get; set; }

    public string head_portrait { get; set; }

    public string last_name { get; set; }

    public string name { get; set; }

    public string name_spell { get; set; }

    public int? nationality { get; set; }

    public string park_blackwhite_id { get; set; }

    public string personnal_list_id { get; set; }

    public string phone { get; set; }

    public string photo_path { get; set; }

    public string pin { get; set; }

    public virtual ICollection<vis_attribute_value> vis_attribute_values { get; set; } = new List<vis_attribute_value>();

    public virtual ICollection<vis_biotemplate> vis_biotemplates { get; set; } = new List<vis_biotemplate>();

    public virtual ICollection<vis_reservation> vis_reservations { get; set; } = new List<vis_reservation>();
}