// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class vis_watchlist
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string address { get; set; }

    public string aliases { get; set; }

    public string category { get; set; }

    public string cert_number { get; set; }

    public string cert_photo { get; set; }

    public string cert_type { get; set; }

    public DateTime? change_time { get; set; }

    public string company { get; set; }

    public int? enabled { get; set; }

    public DateTime? end_watch_time { get; set; }

    public string head_portrait { get; set; }

    public string last_name { get; set; }

    public string name { get; set; }

    public string nationality { get; set; }

    public string nationality_name { get; set; }

    public string phone { get; set; }

    public int? reject_count { get; set; }

    public string reject_dates { get; set; }

    public string remark { get; set; }

    public bool? is_set_watch_time { get; set; }

    public DateTime? start_watch_time { get; set; }

    public string watch_list_type { get; set; }
}