// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class vis_alert_template
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string additional_contact { get; set; }

    public int? advance_send_time { get; set; }

    public string body { get; set; }

    public string bottom { get; set; }

    public short event_type { get; set; }

    public string field { get; set; }

    public bool? init_code { get; set; }

    public string name { get; set; }

    public int? notify_advance { get; set; }

    public bool? send_audit_to_host { get; set; }

    public bool send_expired_advance { get; set; }

    public bool send_to_host { get; set; }

    public bool send_to_hostadvance { get; set; }

    public bool send_to_visitor { get; set; }

    public string subject { get; set; }

    public short template_type { get; set; }

    public virtual ICollection<vis_template_linkage> vis_template_linkages { get; set; } = new List<vis_template_linkage>();
}