// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class vis_transaction
{
    public string id { get; set; }

    public string app_id { get; set; }

    public string bio_tbl_id { get; set; }

    public string company_id { get; set; }

    public DateTime? create_time { get; set; }

    public string creater_code { get; set; }

    public string creater_id { get; set; }

    public string creater_name { get; set; }

    public int? op_version { get; set; }

    public DateTime? update_time { get; set; }

    public string updater_code { get; set; }

    public string updater_id { get; set; }

    public string updater_name { get; set; }

    public string area_name { get; set; }

    public string businesscard_photo { get; set; }

    public string card_no { get; set; }

    public string carried_goods_in { get; set; }

    public string carried_goods_out { get; set; }

    public string cert_photo { get; set; }

    public string enter_goods_photo { get; set; }

    public string enter_photo { get; set; }

    public string enter_place { get; set; }

    public DateTime? enter_time { get; set; }

    public string exit_goods_photo { get; set; }

    public string exit_photo { get; set; }

    public string exit_place { get; set; }

    public DateTime? exit_time { get; set; }

    public short? level_state { get; set; }

    public string person_pwd { get; set; }

    public string personnal_list_id { get; set; }

    public string signature_photo { get; set; }

    public DateTime? valid_end_time { get; set; }

    public DateTime? valid_start_time { get; set; }

    public string vis_company { get; set; }

    public string vis_emp_cert_number { get; set; }

    public string vis_emp_cert_type { get; set; }

    public string vis_emp_id { get; set; }

    public string vis_emp_last_name { get; set; }

    public string vis_emp_name { get; set; }

    public string vis_emp_pin { get; set; }

    public string vis_remark { get; set; }

    public string visit_number { get; set; }

    public string visit_reason { get; set; }

    public short? visit_state { get; set; }

    public string visited_emp_dept { get; set; }

    public string visited_emp_dept_id { get; set; }

    public string visited_emp_id { get; set; }

    public string visited_emp_last_name { get; set; }

    public string visited_emp_name { get; set; }

    public string visited_emp_office_phone { get; set; }

    public string visited_emp_pin { get; set; }

    public int? visitor_count { get; set; }

    public virtual ICollection<vis_visitor_level> vis_visitor_levels { get; set; } = new List<vis_visitor_level>();
}