// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace del.Models;

public partial class wf_flow_node
{
    public string id { get; set; }

    public string expr_condition_value { get; set; }

    public string expression { get; set; }

    public string node_name { get; set; }

    public string node_type { get; set; }

    public string notifier_per_ids { get; set; }

    public short? notifier_type { get; set; }

    public string pers_person_id { get; set; }

    public string pers_position_id { get; set; }

    public string sort_no { get; set; }

    public string flow_id { get; set; }

    public virtual wf_flow flow { get; set; }
}